name: Application CI

on: 
  push: 
    branches :
      - '**/feature/*'
      - 'develop'
      - 'master'
  pull_request:
     branches :
      - 'develop'
      - 'master'    
jobs:  
    #jobs_super-lint:
      #name: Lint code base
      #runs-on: ubuntu-latest
      #steps:
        #- name: Checkout code
          #uses: actions/checkout@v2

        #- name: Run Super-Linter
         # uses: github/super-linter@v3
          #env:
            #DEFAULT_BRANCH: main
            #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    job_build_test:
        #needs: jobs_super-lint
        name: build test backend && frontend ok
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.pull_request.title, '[skip ci]') && !contains(github.event.pull_request.title, '[ci skip]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.16.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.16.1
            - uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Install node.js packages
              run: npm install
            - name: Run backend test
              run: mvn -ntp clean verify -P-webpack
            - name: Run frontend test
              run: npm run test
            
            - name: upload target sharing build
              uses: actions/upload-artifact@v1
              with:
                name: target
                path: target
                retention-days: 1


    
    job_code_quality:
      name: Analyze code with SonarQube
      needs: job_build_test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        
        - name: download target sharing build
          uses: actions/download-artifact@v1
          with:
            name: target

        - name: Analyze code with SonarQube
          env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.GLOBAL_SONAR_TOKEN  }}  #${{ secrets.SONAR_TOKEN }}
          run: |
               if [ -n $SONAR_TOKEN ]; 
               then
                 mvn -ntp initialize sonar:sonar -Dsonar.login=${{ secrets.GLOBAL_SONAR_TOKEN }} -Dsonar.organization=${{ secrets.SONAR_ORGANISATION }} -Dsonar.host.url=${{ secrets.SONAR_URL }}  
                else
                  echo No SONAR_TOKEN, skipping...
                fi


    job_publish_artifact:
      name: Publish artefact  #publish to github package
      needs: job_code_quality
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        
        - name: download target sharing build
          uses: actions/download-artifact@v1
          with:
            name: target
        
        - name: Publish snapshot artefac
          run: mvn -ntp deploy -Pprod -DskipTests #mvn --batch-mode deploy
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    

    job5_release:
      name: publish release #publish to github package
      needs: job_publish_artifact
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
        - uses: actions/setup-java@v1
          with:
            java-version: 11
            architecture: x64
        
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        
        - name: download target sharing build
          uses: actions/download-artifact@v1
          with:
            name: target

        - name: publish release artifact
          continue-on-error: true
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          run: |
               git config --global user.email "j.bilong@gmail.com"
               git config --global user.name "bilonjea"
               mvn -ntp release:prepare release:perform -DskipTests 
  
    job_publish_dockerhub:
      name: publish to docker hub
      needs: job_code_quality #job5_release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11

        - name: download target sharing build
          uses: actions/download-artifact@v1
          with:
            name: target
        
        - name: Build and publish docker image
          if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
          run: |
                GIT_TAG=:${GITHUB_REF#refs/tags/}
                DOCKER_TAG=${GIT_TAG#:refs/heads/master}
                mvn -ntp jib:build -Djib.to.image="${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_INSTANCE_NAME }}${DOCKER_TAG}" -Djib.to.auth.username="${{ secrets.DOCKER_USERNAME }}" -Djib.to.auth.password="${{ secrets.DOCKER_PASSWORD }}"


    #https://github.com/marketplace/actions/deploy-to-heroku  
    jobdeploy:
      name: Deploy to Herroku
      needs: job_code_quality #job5_release
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            branch: "master"
            team: ${{secrets.HEROKU_REPO_TEAM}} 
            buildpack: ${{secrets.HEROKU_BUILD_PACK}}
            



    





