name: Release CI


on: 
  push: 
    branches :
      - '**/feature/*'
      - 'develop'
      - 'master'
  pull_request:
     branches :
      - 'develop'
      - 'master' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

defaults:
  run:
    shell: bash

jobs:  
    job_super-lint:
      name: Lint code base
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run Super-Linter
          uses: github/super-linter@v3
          env:
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    job5_release:
      needs: job_super-lint #job_publish_artifact
      name: publish release #publish to github package
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
        - uses: actions/setup-java@v1
          with:
            java-version: 11
            architecture: x64
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        - name: publish release artifact
          
          run: |
               git config --global user.email "j.bilong@gmail.com"
               git config --global user.name "bilonjea"
               pwd 
               ls -al ~/.m2/
               mvn -ntp release:prepare release:perform -DskipTests 
  
            



    





