name: Release CI


on: 
  push: 
    branches :
      - '**/feature/*'
      - 'develop'
      - 'master'
  pull_request:
     branches :
      - 'develop'
      - 'master' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash

jobs:  

    job5_release:
      name: publish release #publish to github package
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
        - uses: actions/setup-java@v1
          with:
            java-version: 11
            architecture: x64
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        - name: checkout ssh
          run: | 
               ssh-keygen -o -t rsa -q -N ""
              
        - name: publish release artifact
          run: |
               git config --global user.email "j.bilong@gmail.com"
               git config --global user.name "bilonjea"
               mvn -ntp release:prepare release:perform -DskipTests 
  
            



    





