name: Release CI


on: 
  push: 
    branches :
      - '**/feature/*'
      - 'develop'
      - 'master'
  pull_request:
     branches :
      - 'develop'
      - 'master' 
#env:
  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
  #SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash

jobs:  

    job5_release:
      name: publish release #publish to github package
      runs-on: ubuntu-20.04
      steps:
        #- uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
        - uses: actions/setup-java@v1
          with:
            java-version: 11
            architecture: x64
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        - uses: mg-smartrent/github-actions-maven-release@v1.5 #uses: MiniDigger/github-actions-maven-release@v1.10.2 #uses: qcastel/github-actions-maven-release@master
          with:
            release-branch-name: "master"
            git-release-bot-name: "ReleaseBot"
            git-release-bot-email: "release.bot@smartrent.com"
            access-token: ${GITHUB_TOKEN}

            # Release
            maven-repo-server-id: ${MAVEN_SERVER_ID}
            maven-repo-server-username: ${GITHUB_USERNAME}
            maven-repo-server-password: ${GITHUB_TOKEN}
            maven-release-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"

            # Publish artifacts to GitHub Packages
            #maven-publish-args: "-Dskip.unit.tests=true -Dskip.integration.tests=true"
            maven-release-publish: "true"
            maven-snapshot-publish: "true"
            



    





