name: Release CI


on: 
  push: 
    branches :
      - '**/feature/*'
      - 'develop'
      - 'master'
  pull_request:
     branches :
      - 'develop'
      - 'master' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

defaults:
  run:
    shell: bash

jobs:  

    job5_release:
      name: publish release #publish to github package
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2 # The checkout step downloads a copy of your repository on the runner.
        - uses: actions/setup-java@v1
          with:
            java-version: 11
            architecture: x64
        - uses: actions/setup-node@v1
          with:
            node-version: 12.16.1
        - uses: MiniDigger/github-actions-maven-release@v1.10.2 #uses: qcastel/github-actions-maven-release@master
          with:
              release-branch-name: "master"
              git-release-bot-name: "bilonjea"
              git-release-bot-email: "j.bilong@gmail.com"
              access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
              maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Ddockerfile.skip -DdockerCompose.skip"
            



    





